#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'awscli',
  git: 'https://github.com/shlomoswidler/awscli.git'

cookbook 'murmur-too',
  path: 'site-cookbooks/murmur-too'

cookbook 'ncv-murmur',
  path: 'site-cookbooks/ncv-murmur'
